### ISSUE TITLE
In Elgg 1.9.6, changed Group Access permissions not obeyed by Tidypics photos & albums 

### ISSUE THREAD

**Issue by dranii** [iionly/Elgg_1.9_tidypics#10]
Create a Group ABC by User A
Set "Accessibility of group content" :Unrestricted
Create a Group Album
Upload a photo 'xyz' to this album
Let user B (who is not a friend of user A) visit /photos/siteimagesall and/or visit the photo page of photo 'xyz'
User B can see this photo and this is expected as the Group had Unrestricted Access
Now User A sets "Accessibility of group content" :Members only
User B cannot see the Group ABC activities, blog etc
BUT when user B visits the /photos/siteimagesall and/or visits the photo page of photo 'xyz' user B can still see this photo

However, a blog post *cannot* be anymore seen if a Group has been made Members only.
Can we please make the photo post (albums and or photo) change access permissions when the Group permissions also change like core Blog / File etc?

If not ( or even if yes) can Tidypics settings have a control to set off Group photo (and album) if wanted by the site super admin?

**Comment by iionly** [comment]
Fixed with commit https://github.com/iionly/Elgg_1.9_tidypics/commit/d7273f729b465bc897a12f377d8b5015ec1c1cb2. This will be part of Tidypics 1.9.5,

With this change the access to the full view of group albums and group images in restricted groups is no longer possible for users who are not member of the group. But it's important to keep in mind that the visibility of group images and albums in list views (e,g. "All images" or "All albums") depends ONLY on the access level of the album! This is a corresponding behaviour to other type of content (e.g. blogs). If you make a group a restricted group, the access level of existing content is NOT changed.

The group modules albums and images can already be disabled within a group's settings page.
